name = "PSOI"
uuid = "d7b152a3-b3b9-410e-ba0d-b3c9d42775b0"
authors = ["Stepan Oslejsek"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.11.0"
MathOptInterface = "1.40.1"
StaticArrays = "1.9.13"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
