name = "PSOI"
uuid = "d7b152a3-b3b9-410e-ba0d-b3c9d42775b0"
authors = ["Stepan Oslejsek"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
